### ISSUE TITLE
Panic on debug run

### ISSUE THREAD

**Issue by sigmaSd** [lotabout/tuikit#1]
Hi, here is the error (rust 1.32)
```
cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/repl-rs`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: StringError("term:get_cursor_pos failed to get CPR response after max retries")', src/libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
and it works normally when I use RUST_BACKTRACE=1 (fails sometimes)
So here is a heisenbug as your first issue^^
EDIT: also cargo run --release works (sometimes)
EDIT2: it failes on this line:
```rust

 let term = Term::with_height(TermHeight::Percent(30)).unwrap();

 ```
EDIT3: failes using vscode terminal, gnome-terminal, xfce4-terminal and I probably should mention I'm on wayland,
works 100% on xterm

**Comment by lotabout** [comment]
@sigmaSd Could you please paste the value `$TERM` along with the terminal?

For "percent height" to work, tuikit must know the current cursor position(CPR) and apparently some terminal doesn't support it (though most xterm compatible terminals would work). And I did try it with vscode terminal(on Mac) and it works fine.

**Comment by sigmaSd** [comment]
@lotabout gnome-terminal xterm-256color

**Comment by sigmaSd** [comment]
xterm also fails sometimes, I tried it on x instead of wayland it looks like it works consistently.
Increasing the wait_timeout (to 40ms in my case) https://github.com/lotabout/tuikit/blob/master/src/term.rs#L48 apparently fixed the issue (fixed as in fails way less more).

**Comment by totph** [comment]
I am seeing the same issue, even with `Term::with_height(TermHeight::Fixed(12))`. Rarely happens on xterm in release mode and quite frequently in gnome-terminal. Also after exiting some stray control characters are left over:

    if term.is_err() {
      println!("tuikit error");
      std::process::exit(1);
    }

Terminal (with PS1='$')

    $while target/release/testterm; do :; done
    [...]
    tuikit error
    $;1R

**Comment by lotabout** [comment]
@sigmaSd Let me confirm: increasing the wait_timeout will work in all cases right?
Seems that I should consider different terminal speed for reporting CPR result.

**Comment by lotabout** [comment]
@totph Thanks for reporting and I understand the problem.

Besides, as long as we don't request a "fullscreen" terminal, tuikit need to know the current position to work properly. And the current problem seems to be that terminal is too slow(> 20ms) at reporting the cursor position.

As you see in your output, CPR report cursor position as `ESC[<row>;<col>R`. And it arrived AFTER tuikit exits.

**Comment by lotabout** [comment]
Please try to latest git version:

```toml
[dependencies]
tuikit = { git = "https://github.com/lotabout/tuikit.git" }
```

**Comment by totph** [comment]
That indeed fixes it for me, thank you!
