### ISSUE TITLE
examples/split.rs: printed out string cannot be seen

### ISSUE THREAD

**Issue by ngirard** [lotabout/tuikit#10]
After compiling & running `examples/split.rs`, I cannot see on my screen the result of [this line](https://github.com/lotabout/tuikit/blob/a4c602e7f1a4fe737f83bcbd8db6ff98fad949a8/examples/split.rs#L40):
```rust
let _ = term.print(0, 0, "press 'q' to exit");
```

**Comment by lotabout** [comment]
@ngirard Thanks for report. It's actually expected that it won't print, since the screen was overwritten by the splits.

I've modified the example to avoid confusion.
