### ISSUE TITLE
Windows support for tuikit? 

### ISSUE THREAD

**Issue by bgianfo** [lotabout/tuikit#13]
Is here any  chance of  adding windows support to tuikit? 
It seems to use a bunch of UNIX specific functionality?

**Comment by lotabout** [comment]
Sorry for really late response. Basically tuikit uses the following UNIX specific features:

1. use `fcntl` to support non-blocking file read (of user input).
2. use `ioctl` to get terminal size.
3. use `sigaction` to register handler over terminal resize.

And you could find the related code at `sys` directory.

Unfortunately I'm not familiar with Windows's API. Sorry that I'll not add the support myself. PRs are welcome though.

**Comment by prabirshrestha** [comment]
Seems like [skim](https://github.com/lotabout/skim) uses tuikit so it also doesn't work in windows.

What about using existing libraries such as [termwiz](https://docs.rs/termwiz/) or [crossterm](https://github.com/crossterm-rs/crossterm) that works in pure rust and is cross platform. Both supports non blocking as well as getting terminal size as well as resize events.

TermWiz is also quite interesting as it has first class support for [BufferredTerminal](https://github.com/wez/wezterm/blob/master/termwiz/examples/buffered_terminal.rs) as well as [Widgets](https://github.com/wez/wezterm/blob/master/termwiz/examples/widgets_basic.rs).

**Comment by Kreijstal** [comment]
> Seems like [skim](https://github.com/lotabout/skim) uses tuikit so it also doesn't work in windows.
> 
> What about using existing libraries such as [termwiz](https://docs.rs/termwiz/) or [crossterm](https://github.com/crossterm-rs/crossterm) that works in pure rust and is cross platform. Both supports non blocking as well as getting terminal size as well as resize events.
> 
> TermWiz is also quite interesting as it has first class support for [BufferredTerminal](https://github.com/wez/wezterm/blob/master/termwiz/examples/buffered_terminal.rs) as well as [Widgets](https://github.com/wez/wezterm/blob/master/termwiz/examples/widgets_basic.rs).

maybe a wrapper for windows that uses termwiz?
