### ISSUE TITLE
Scrolldown when printings reach the terminal's end

### ISSUE THREAD

**Issue by sigmaSd** [lotabout/tuikit#2]
Right now printings disappear after reaching the end of the terminal would be a great feature to scroll down automatically

**Comment by sigmaSd** [comment]
Ah thought that that's what ipython is doing, now that I checked its just repainting all the last entries, maybe that means this is an unrealistic feature request, I guess I'll probably close the issue

**Comment by lotabout** [comment]
@sigmaSd Let me confirm what you mean by "scroll"? Suppose we allocate a screen with 3 lines, which one of the following

```
1 |                      |
2 |                 xxxxx| <- wrap to next line?
3 |xxx                   |
```

```
1 |                      |
2 |                      |
3 |                 xxxxx|
   xxx                     <- create a new line and possibly show scroll bar?
```

Besides, `Term` is at the lowest level and will only treat the screen as a table of cells and nothing else.
What you'd like to have is some "widgets" that could handle buffering and scrolling. I am currently working on another project that try to do similar things. But right now, you have to handle it by yourself.

**Comment by sigmaSd** [comment]
I mean the second one `create a new line and possibly show scroll bar`, I understand I'll just handle it for now, thanks for the infos!
